apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/sonarqube" # Ð?m b?o thu m?c này t?n t?i trên Worker Node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: sonarqube # Thay b?ng namespace c?a b?n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi