apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/instance: sonarqube
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: sonarqube-system
spec:
  type: NodePort
  selector:
    # Quan trọng: Phải khớp với nhãn trong template của Deployment
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/instance: sonarqube
  ports:
    - name: http
      protocol: TCP
      port: 9000       # Cổng của Service bên trong Cluster
      targetPort: 9000 # Cổng mà Container SonarQube đang lắng nghe
      nodePort: 31000
